#!/usr/bin/env bash
# check if the command "which asdf" returns no such file or directory
output=$(pwd) # redirect stderr to stdout
if [[ $output == "/mnt/c/Repos/"* ]]; then
	exec git.exe "$@"
else
	exec git2 "$@"
fi
